/**
 * @module store
 * This module manages the entire state of the application using Svelte stores.
 * It handles file data, UI state, user selections, history (undo/redo),
 * and clipboard operations.
 */
import { writable, get } from 'svelte/store';
import type { MenuItem } from '$lib/components/ContextMenu.svelte';

/**
 * @interface Tag
 * Represents a single metadata tag.
 */
export interface Tag {
  /** The name of the tag (e.g., "ARTIST"). */
  Name: string;
  /** The value of the tag (e.g., "The Beatles"). */
  String: string;
  /** A unique client-side identifier for UI purposes. */
  id?: string;
}

/**
 * @interface Track
 * Represents a track within the media file (e.g., a video or audio stream).
 */
export interface Track {
  /** A display-friendly name generated by the UI (e.g., "Video #1"). */
  display_name: string;
  /** The optional name of the track, from the file's metadata. */
  track_name?: string;
  /** A list of tags associated with this track. */
  tags: Tag[];
  /** A unique client-side identifier for UI purposes. */
  id?: string;
}

/**
 * @interface FileData
 * Represents the entire structure of tags extracted from a Matroska file.
 */
export interface FileData {
  /** Tags that apply to the file as a whole. */
  global_tags: Tag[];
  /** A list of tracks contained within the file. */
  tracks: Track[];
  /** The absolute path to the file. */
  path?: string;
}

/**
 * Traverses the file data and assigns a unique `id` to every track and tag if it doesn't have one.
 * This is crucial for Svelte's keyed `each` blocks and for tracking selections.
 * @param data The file data to process.
 * @returns The processed file data with unique IDs.
 */
function addUniqueIds(data: FileData): FileData {
  let counter = 0;
  const generateId = () => `tag-${Date.now()}-${counter++}`;

  data.global_tags.forEach(tag => {
    if (!tag.id) tag.id = generateId();
  });
  data.tracks.forEach(track => {
    if (!track.id) track.id = generateId();
    track.tags.forEach(tag => {
      if (!tag.id) tag.id = generateId();
    });
  });
  return data;
}

/** The initial, empty state for the file data. */
const initialData: FileData = {
  global_tags: [],
  tracks: [],
};

/**
 * The main application store.
 * @property {FileData} fileData - The core data of the currently loaded file.
 * @property {string} path - The absolute path of the loaded file.
 * @property {Set<string>} selectedTagIds - A set of IDs of the currently selected tags.
 * @property {string | null} lastSelectedId - The ID of the last tag that was selected, used for shift-click selections.
 * @property {string | null} selectedContext - The ID of the context area (a track ID or "global") that is currently active.
 * @property {string | null} newlyAddedTagId - The ID of a tag that was just added, used to trigger inline editing.
 * @property {Tag[]} clipboard - An array of tags that have been cut or copied.
 * @property {FileData[]} history - An array of `FileData` snapshots for undo/redo functionality.
 * @property {number} historyIndex - The current position in the history array.
 * @property {boolean} isDirty - A flag indicating if there are unsaved changes.
 * @property {number} savedHistoryIndex - The history index at the time of the last save.
 */
const { subscribe, update } = writable({
  fileData: initialData,
  path: '',
  selectedTagIds: new Set<string>(),
  lastSelectedId: null as string | null,
  selectedContext: null as string | null,
  newlyAddedTagId: null as string | null,
  clipboard: [] as Tag[],
  history: [] as FileData[],
  historyIndex: -1,
  isDirty: false,
  savedHistoryIndex: -1,
});

/**
 * @interface ContextMenuState
 * Represents the state of the custom context menu.
 */
interface ContextMenuState {
  /** Whether the context menu is currently visible. */
  show: boolean;
  /** The x-coordinate for the menu's position. */
  x: number;
  /** The y-coordinate for the menu's position. */
  y: number;
  /** The list of items to display in the menu. */
  items: MenuItem[];
}

const { subscribe: contextMenuSubscribe, update: contextMenuUpdate } = writable<ContextMenuState>({
  show: false,
  x: 0,
  y: 0,
  items: [],
});

/**
 * A store to manage the state of the right-click context menu.
 */
export const contextMenuStore = {
  subscribe: contextMenuSubscribe,
  /**
   * Opens the context menu at a specific position with a given set of items.
   * @param {number} x - The x-coordinate (horizontal position).
   * @param {number} y - The y-coordinate (vertical position).
   * @param {MenuItem[]} items - The menu items to display.
   */
  open: (x: number, y: number, items: MenuItem[]) => {
    contextMenuUpdate(state => {
      state.show = true;
      state.x = x;
      state.y = y;
      state.items = items;
      return state;
    });
  },
  /** Closes the context menu. */
  close: () => {
    contextMenuUpdate(state => {
      state.show = false;
      return state;
    });
  }
};

/**
 * The main store for managing tag data and related UI state.
 * It encapsulates all operations related to loading, modifying, and saving tags.
 */
export const tagStore = {
  subscribe,

  /**
   * Loads new file data into the store, resetting the state.
   * @param {FileData} data - The file data parsed from the Matroska file.
   * @param {string} path - The absolute path of the file.
   */
  loadFile: (data: FileData, path: string) => {
    const dataWithIds = addUniqueIds(data);
    update(state => {
      const newState = {
        ...state,
        fileData: dataWithIds,
        path: path,
        selectedTagIds: new Set<string>(),
        selectedContext: 'global',
        history: [JSON.parse(JSON.stringify(dataWithIds))],
        historyIndex: 0,
        isDirty: false,
        savedHistoryIndex: 0,
      };
      return newState;
    });
  },

  /**
   * Toggles the selection state of a tag based on user interaction.
   * Supports single selection, multi-selection with Ctrl/Meta, and range selection with Shift.
   * @param {string} tagId - The ID of the tag being interacted with.
   * @param {MouseEvent} event - The mouse event that triggered the selection.
   */
  toggleSelection: (tagId: string, event: MouseEvent) => {
    update(state => {
      const newSelectedIds = new Set(state.selectedTagIds);
      const { ctrlKey, metaKey, shiftKey } = event;

      if (shiftKey && state.lastSelectedId) {
        const allTags: Tag[] = [...state.fileData.global_tags, ...state.fileData.tracks.flatMap(t => t.tags)];
        const lastIndex = allTags.findIndex(t => t.id === state.lastSelectedId);
        const currentIndex = allTags.findIndex(t => t.id === tagId);

        if (lastIndex !== -1 && currentIndex !== -1) {
          const start = Math.min(lastIndex, currentIndex);
          const end = Math.max(lastIndex, currentIndex);
          if (!ctrlKey && !metaKey) {
            newSelectedIds.clear();
          }
          for (let i = start; i <= end; i++) {
            newSelectedIds.add(allTags[i].id!);
          }
        }
      } else if (ctrlKey || metaKey) {
        if (newSelectedIds.has(tagId)) {
          newSelectedIds.delete(tagId);
        } else {
          newSelectedIds.add(tagId);
        }
      } else {
        if (newSelectedIds.has(tagId) && newSelectedIds.size === 1) {
          newSelectedIds.clear();
        } else {
          newSelectedIds.clear();
          newSelectedIds.add(tagId);
        }
      }

      state.selectedTagIds = newSelectedIds;
      state.lastSelectedId = tagId;

      let contextFound = false;
      if (state.fileData.global_tags.some(t => t.id === tagId)) {
        state.selectedContext = 'global';
        contextFound = true;
      } else {
        for (const track of state.fileData.tracks) {
          if (track.tags.some(t => t.id === tagId)) {
            state.selectedContext = track.id!;
            contextFound = true;
            break;
          }
        }
      }
      if (!contextFound) {
        state.selectedContext = null;
      }

      return state;
    });
  },

  /**
   * Updates the properties of a specific tag.
   * @param {string} trackId - The ID of the track containing the tag, or "global".
   * @param {string} tagId - The ID of the tag to update.
   * @param {Partial<Tag>} newTag - An object containing the new values for the tag.
   */
  updateTag: (trackId: string, tagId: string, newTag: Partial<Tag>) => {
    update(state => {
      const newData = JSON.parse(JSON.stringify(state.fileData));
      let tagToUpdate: Tag | undefined;

      if (trackId === 'global') {
        tagToUpdate = newData.global_tags.find((t: Tag) => t.id === tagId);
      } else {
        const track = newData.tracks.find((t: Track) => t.id === trackId);
        if (track) {
          tagToUpdate = track.tags.find((t: Tag) => t.id === tagId);
        }
      }

      if (tagToUpdate) {
        Object.assign(tagToUpdate, newTag);
      }

      state.history = state.history.slice(0, state.historyIndex + 1);
      state.history.push(newData);
      state.historyIndex++;

      state.fileData = newData;
      state.isDirty = state.historyIndex !== state.savedHistoryIndex;
      return state;
    });
  },

  /**
   * Sets the currently active context for operations like adding or pasting tags.
   * @param {string | null} context - The ID of the context (e.g., a track ID or "global").
   */
  setSelectedContext: (context: string | null) => {
    update(state => {
      state.selectedContext = context;
      return state;
    });
  },

  /**
   * Clears all tag selections and resets the selected context.
   */
  clearSelections: () => {
    update(state => {
      state.selectedTagIds.clear();
      state.selectedContext = null;
      return state;
    });
  },

  /**
   * Adds a new, empty tag to the currently selected context.
   * If no context is selected, it adds the tag to the global tags.
   * It also sets `newlyAddedTagId` to trigger inline editing in the UI.
   */
  addTag: () => {
    update(state => {
      const newData = JSON.parse(JSON.stringify(state.fileData));
      const newTag: Tag = { Name: "", String: "", id: `tag-${Date.now()}-${Math.random()}` };

      if (state.selectedContext === 'global') {
        newData.global_tags.push(newTag);
      } else if (state.selectedContext) {
        const targetTrack = newData.tracks.find((t: Track) => t.id === state.selectedContext);
        if (targetTrack) {
          targetTrack.tags.push(newTag);
        } else {
          newData.global_tags.push(newTag);
        }
      } else {
        newData.global_tags.push(newTag);
      }

      state.history = state.history.slice(0, state.historyIndex + 1);
      state.history.push(newData);
      state.historyIndex++;
      state.fileData = newData;
      state.newlyAddedTagId = newTag.id!;
      state.isDirty = state.historyIndex !== state.savedHistoryIndex;
      return state;
    });
  },

  /**
   * Resets the `newlyAddedTagId` state, typically after the inline editor has been activated.
   */
  clearNewlyAddedTagId: () => {
    update(state => {
      state.newlyAddedTagId = null;
      return state;
    });
  },

  /**
   * Deletes all currently selected tags.
   * If no tags are selected but a context is active, it deletes all tags within that context.
   */
  deleteSelectedTags: () => {
    update(state => {
      const newData = JSON.parse(JSON.stringify(state.fileData));
      let changed = false;

      if (state.selectedTagIds.size > 0) {
        const initialGlobalCount = newData.global_tags.length;
        newData.global_tags = newData.global_tags.filter((t: Tag) => !state.selectedTagIds.has(t.id!));
        if (newData.global_tags.length !== initialGlobalCount) changed = true;

        newData.tracks.forEach((track: Track) => {
          const initialTrackTagCount = track.tags.length;
          track.tags = track.tags.filter((t: Tag) => !state.selectedTagIds.has(t.id!));
          if (track.tags.length !== initialTrackTagCount) changed = true;
        });

        state.selectedTagIds.clear();

      } else if (state.selectedContext) {
        if (state.selectedContext === 'global') {
          if (newData.global_tags.length > 0) {
            newData.global_tags = [];
            changed = true;
          }
        } else {
          const targetTrack = newData.tracks.find((t: Track) => t.id === state.selectedContext);
          if (targetTrack && targetTrack.tags.length > 0) {
            targetTrack.tags = [];
            changed = true;
          }
        }
      }

      if (changed) {
        state.history = state.history.slice(0, state.historyIndex + 1);
        state.history.push(newData);
        state.historyIndex++;
        state.fileData = newData;
        state.isDirty = state.historyIndex !== state.savedHistoryIndex;
      }

      return state;
    });
  },

  /**
   * Copies the selected tags to the internal clipboard.
   * If no tags are selected, it copies all tags from the active context.
   */
  copySelectedTags: () => {
    update(state => {
      let tagsToCopy: Tag[] = [];
      if (state.selectedTagIds.size > 0) {
        const allTags = [...state.fileData.global_tags, ...state.fileData.tracks.flatMap(t => t.tags)];
        tagsToCopy = allTags.filter(t => state.selectedTagIds.has(t.id!));
      } else if (state.selectedContext) {
        if (state.selectedContext === 'global') {
          tagsToCopy = [...state.fileData.global_tags];
        } else {
          const targetTrack = state.fileData.tracks.find(t => t.id === state.selectedContext);
          if (targetTrack) {
            tagsToCopy = [...targetTrack.tags];
          }
        }
      }
      state.clipboard = tagsToCopy;
      return state;
    });
  },

  /**
   * Cuts the selected tags, copying them to the clipboard and removing them from the data.
   * If no tags are selected, it cuts all tags from the active context.
   */
  cutSelectedTags: () => {
    update(state => {
      let tagsToCopy: Tag[] = [];
      if (state.selectedTagIds.size > 0) {
        const allTags = [...state.fileData.global_tags, ...state.fileData.tracks.flatMap(t => t.tags)];
        tagsToCopy = allTags.filter(t => state.selectedTagIds.has(t.id!));
      } else if (state.selectedContext) {
        if (state.selectedContext === 'global') {
          tagsToCopy = [...state.fileData.global_tags];
        } else {
          const targetTrack = state.fileData.tracks.find(t => t.id === state.selectedContext);
          if (targetTrack) {
            tagsToCopy = [...targetTrack.tags];
          }
        }
      }
      state.clipboard = tagsToCopy;

      if (state.clipboard.length === 0) return state;

      const newData = JSON.parse(JSON.stringify(state.fileData));
      let changed = false;

      if (state.selectedTagIds.size > 0) {
        const idsToDelete = new Set(state.selectedTagIds);
        const initialGlobalCount = newData.global_tags.length;
        newData.global_tags = newData.global_tags.filter((t: Tag) => !idsToDelete.has(t.id!));
        if (newData.global_tags.length !== initialGlobalCount) changed = true;

        newData.tracks.forEach((track: Track) => {
          const initialTrackTagCount = track.tags.length;
          track.tags = track.tags.filter((t: Tag) => !idsToDelete.has(t.id!));
          if (track.tags.length !== initialTrackTagCount) changed = true;
        });

        state.selectedTagIds.clear();

      } else if (state.selectedContext) {
        if (state.selectedContext === 'global') {
          if (newData.global_tags.length > 0) {
            newData.global_tags = [];
            changed = true;
          }
        } else {
          const targetTrack = newData.tracks.find((t: Track) => t.id === state.selectedContext);
          if (targetTrack && targetTrack.tags.length > 0) {
            targetTrack.tags = [];
            changed = true;
          }
        }
      }

      if (!changed) return state;

      state.history = state.history.slice(0, state.historyIndex + 1);
      state.history.push(newData);
      state.historyIndex++;
      state.fileData = newData;
      state.selectedTagIds.clear();
      state.isDirty = state.historyIndex !== state.savedHistoryIndex;
      return state;
    });
  },

  /**
   * Pastes tags from the clipboard into the data.
   * Tags are inserted after the `lastSelectedId` if it exists, otherwise they are appended
   * to the `selectedContext`. If neither exists, they are added to the global tags.
   */
  pasteTags: () => {
    update(state => {
      if (state.clipboard.length === 0) return state;

      const newData = JSON.parse(JSON.stringify(state.fileData));
      const newTags = state.clipboard.map((t: Tag) => ({ ...t, id: `tag-${Date.now()}-${Math.random()}` }));
      let pasted = false;

      if (state.lastSelectedId && state.selectedTagIds.size > 0) {
        let tagIndex = newData.global_tags.findIndex((t: Tag) => t.id === state.lastSelectedId);
        if (tagIndex !== -1) {
          newData.global_tags.splice(tagIndex + 1, 0, ...newTags);
          pasted = true;
        } else {
          for (const track of newData.tracks) {
            tagIndex = track.tags.findIndex((t: Tag) => t.id === state.lastSelectedId);
            if (tagIndex !== -1) {
              track.tags.splice(tagIndex + 1, 0, ...newTags);
              pasted = true;
              break;
            }
          }
        }
      }

      if (!pasted && state.selectedContext) {
        if (state.selectedContext === 'global') {
          newData.global_tags.push(...newTags);
          pasted = true;
        } else {
          const targetTrack = newData.tracks.find((t: Track) => t.id === state.selectedContext);
          if (targetTrack) {
            targetTrack.tags.push(...newTags);
            pasted = true;
          }
        }
      }

      if (!pasted) {
        newData.global_tags.push(...newTags);
      }

      state.history = state.history.slice(0, state.historyIndex + 1);
      state.history.push(newData);
      state.historyIndex++;
      state.fileData = newData;
      state.isDirty = state.historyIndex !== state.savedHistoryIndex;
      return state;
    });
  },

  /**
   * Reverts the file data to the previous state in the history.
   */
  undo: () => {
    update(state => {
      if (state.historyIndex > 0) {
        state.historyIndex--;
        state.fileData = JSON.parse(JSON.stringify(state.history[state.historyIndex]));
        state.selectedTagIds.clear();
        state.isDirty = state.historyIndex !== state.savedHistoryIndex;
      }
      return state;
    });
  },

  /**
   * Applies the next state from the history, redoing a previously undone action.
   */
  redo: () => {
    update(state => {
      if (state.historyIndex < state.history.length - 1) {
        state.historyIndex++;
        state.fileData = JSON.parse(JSON.stringify(state.history[state.historyIndex]));
        state.selectedTagIds.clear();
        state.isDirty = state.historyIndex !== state.savedHistoryIndex;
      }
      return state;
    });
  },

  /**
   * Selects all tags across all tracks and global tags.
   */
  selectAllTags: () => {
    update(state => {
      const allTagIds = new Set<string>();
      state.fileData.global_tags.forEach(t => allTagIds.add(t.id!));
      state.fileData.tracks.forEach(track => {
        track.tags.forEach(t => allTagIds.add(t.id!));
      });
      state.selectedTagIds = allTagIds;
      return state;
    });
  },

  /**
   * Moves a tag from one position to another, handling drag-and-drop operations.
   * @param {string} draggedId - The ID of the tag being dragged.
   * @param {string} targetId - The ID of the target tag or track.
   * @param {'before' | 'after' | 'append'} position - The position relative to the target where the tag should be dropped.
   */
  moveTag: (draggedId: string, targetId: string, position: 'before' | 'after' | 'append') => {
    update(state => {
      const newData = JSON.parse(JSON.stringify(state.fileData));

      let draggedTag: Tag | null = null;
      let found = false;

      const globalIndex = newData.global_tags.findIndex((t: Tag) => t.id === draggedId);
      if (globalIndex > -1) {
        draggedTag = newData.global_tags.splice(globalIndex, 1)[0];
        found = true;
      }

      if (!found) {
        for (const track of newData.tracks) {
          const trackIndex = track.tags.findIndex((t: Tag) => t.id === draggedId);
          if (trackIndex > -1) {
            draggedTag = track.tags.splice(trackIndex, 1)[0];
            break;
          }
        }
      }

      if (!draggedTag) return state;

      let targetFound = false;

      if (position === 'append') {
        if (targetId === 'global') {
          newData.global_tags.push(draggedTag);
          targetFound = true;
        } else {
          const targetTrack = newData.tracks.find((t: Track) => t.id === targetId);
          if (targetTrack) {
            targetTrack.tags.push(draggedTag);
            targetFound = true;
          }
        }
      } else {
        const targetGlobalIndex = newData.global_tags.findIndex((t: Tag) => t.id === targetId);
        if (targetGlobalIndex > -1) {
          const insertIndex = position === 'before' ? targetGlobalIndex : targetGlobalIndex + 1;
          newData.global_tags.splice(insertIndex, 0, draggedTag);
          targetFound = true;
        }

        if (!targetFound) {
          for (const track of newData.tracks) {
            const targetTrackIndex = track.tags.findIndex((t: Tag) => t.id === targetId);
            if (targetTrackIndex > -1) {
              const insertIndex = position === 'before' ? targetTrackIndex : targetTrackIndex + 1;
              track.tags.splice(insertIndex, 0, draggedTag);
              targetFound = true;
              break;
            }
          }
        }
      }

      if (targetFound) {
        state.history = state.history.slice(0, state.historyIndex + 1);
        state.history.push(newData);
        state.historyIndex++;
        state.fileData = newData;
        state.isDirty = state.historyIndex !== state.savedHistoryIndex;
      }

      return state;
    });
  },
  /**
   * Saves the current `fileData` back to the original file path.
   * It serializes the data, sends it to the Rust backend via a Tauri command,
   * and updates the `isDirty` and `savedHistoryIndex` state upon success.
   */
  save: async () => {
    console.log("[FRONTEND] Save function triggered.");
    const state = get(tagStore);

    console.log("[FRONTEND] Current state on save:", { isDirty: state.isDirty, path: state.path });
    if (!state.path) {
      console.log("[FRONTEND] Save aborted: No path.");
      return;
    }

    const allTags: Tag[] = [...state.fileData.global_tags, ...state.fileData.tracks.flatMap((t: Track) => t.tags)];
    if (allTags.some(t => !t.Name || !t.String)) {
      console.log("[FRONTEND] Save aborted: Validation failed (empty tag name or value).");
      const { message } = await import('@tauri-apps/plugin-dialog');
      await message('All tags must have a name and a value.', { title: 'Validation Error', kind: 'error' });
      return;
    }

    const getSaveData = (): FileData => {
      const cleanData = JSON.parse(JSON.stringify(state.fileData));
      delete cleanData.path;
      cleanData.global_tags.forEach((t: any) => delete t.id);
      cleanData.tracks.forEach((tr: any) => {
        delete tr.id;
        tr.tags.forEach((t: any) => delete t.id);
      });
      return cleanData;
    };

    try {
      const { invoke } = await import('@tauri-apps/api/core');
      const saveData = getSaveData();
      console.log("[FRONTEND] Invoking 'save_file_data' with path:", state.path);
      console.log("[FRONTEND] Data being sent to backend:", JSON.stringify(saveData, null, 2));
      await invoke('save_file_data', { path: state.path, jsonData: JSON.stringify(saveData) });

      console.log('[FRONTEND] Save successful');
      update(s => {
        s.isDirty = false;
        s.savedHistoryIndex = s.historyIndex;
        return s;
      });
    } catch (err) {
      console.error('[FRONTEND] Save failed', err);
      const { message } = await import('@tauri-apps/plugin-dialog');
      await message(`Failed to save file: ${err}`, { title: 'Save Error', kind: 'error' });
    }
  },
};