use serde::{Deserialize, Serialize, Deserializer, Serializer};
use tauri::Emitter;
use tauri_plugin_dialog::DialogExt;
use tauri_plugin_log::{Target, TargetKind};
use tokio::process::Command as AsyncCommand;
use futures::future;
use tokio::sync::oneshot;
use std::fs::File;
use matroska::Matroska;

mod drop;

/// Creates a new `AsyncCommand` for a given program name.
/// On Windows, it adds the `CREATE_NO_WINDOW` flag to prevent console windows from appearing.
fn create_command(name: &str) -> AsyncCommand {
    let mut cmd = AsyncCommand::new(name);
    #[cfg(windows)]
    {
        const CREATE_NO_WINDOW: u32 = 0x08000000;
        cmd.creation_flags(CREATE_NO_WINDOW);
    }
    cmd
}

/// Custom serializer for `u64` to `String` for JSON compatibility.
fn u64_to_string<S>(x: &u64, s: S) -> Result<S::Ok, S::Error>
where
    S: Serializer,
{
    s.serialize_str(&x.to_string())
}

/// Custom deserializer for `String` to `u64` for JSON compatibility.
fn string_to_u64<'de, D>(deserializer: D) -> Result<u64, D::Error>
where
    D: Deserializer<'de>,
{
    String::deserialize(deserializer)?.parse::<u64>().map_err(serde::de::Error::custom)
}

/// Represents a simple metadata tag, equivalent to the frontend's `Tag` interface.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct SimpleTag {
    /// The name of the tag (e.g., "ARTIST").
    #[serde(rename = "Name")]
    name: String,
    /// The value of the tag (e.g., "The Beatles").
    #[serde(rename = "String")]
    string: String,
    /// The language of the tag value, following IETF BCP 47.
    #[serde(rename = "TagLanguageIETF", default)]
    language: Option<String>,
}

/// Represents a track within the media file, equivalent to the frontend's `Track` interface.
#[derive(Debug, Serialize, Deserialize, Default, Clone)]
pub struct Track {
    /// A display-friendly name generated by the UI (e.g., "Video #1").
    display_name: String,
    /// The codec of the track (e.g., "V_MPEG4/ISO/AVC").
    codec: String,
    /// The track ID from the container.
    #[serde(default)]
    id: u64,
    /// The optional name of the track from metadata.
    track_name: Option<String>,
    /// The unique track identifier (UID).
    #[serde(serialize_with = "u64_to_string", deserialize_with = "string_to_u64")]
    uid: u64,
    /// A list of tags associated with this track.
    tags: Vec<SimpleTag>,
}

/// Represents the entire structure of tags from a file, equivalent to the frontend's `FileData` interface.
#[derive(Debug, Serialize, Deserialize, Default)]
pub struct FileData {
    /// Tags that apply to the file as a whole.
    global_tags: Vec<SimpleTag>,
    /// A list of tracks contained within the file.
    tracks: Vec<Track>,
}



/// A simple command for testing frontend-backend communication.
#[tauri::command]
fn greet(name: &str) -> String {
    format!("Hello, {}! You've been greeted from Rust!", name)
}

/// Opens a native file dialog to allow the user to select a Matroska file.
#[tauri::command]
async fn open_file_dialog(app: tauri::AppHandle) -> Option<String> {
    let (tx, rx) = oneshot::channel();
    app.dialog()
        .file()
        .add_filter("Matroska", &["mkv", "mk3d", "mka", "mks"])
        .pick_file(move |file_path| {
            let result = file_path.map(|p| p.to_string());
            tx.send(result).unwrap();
        });
    rx.await.unwrap_or(None)
}

/// Extracts all track and tag metadata from a given Matroska file.
///
/// This function natively parses the Matroska file using the `matroska` crate.
/// It reads the file's track information and tags, then maps them into a
/// `FileData` struct suitable for the frontend.
///
/// # Arguments
///
/// * `path` - The absolute path to the Matroska file.
///
/// # Errors
///
/// This function will return an error if the file cannot be opened or if the file
/// content cannot be parsed as a valid Matroska file.
#[tauri::command]
async fn get_file_data(path: String) -> Result<FileData, String> {
    log::info!("Getting file data for: {}", path);

    // 1. Open file and parse with matroska crate
    let file = File::open(&path).map_err(|e| e.to_string())?;
    let mkv = Matroska::open(file).map_err(|e| e.to_string())?;

    // 2. Process tracks
    let mut video_count = 1;
    let mut audio_count = 1;
    let mut subtitle_count = 1;

    let mut tracks: Vec<Track> = mkv.tracks.iter().map(|t| {
        let display_name = match t.tracktype {
            matroska::Tracktype::Video => {
                let name = format!("Video#{}", video_count);
                video_count += 1;
                name
            }
            matroska::Tracktype::Audio => {
                let name = format!("Audio#{}", audio_count);
                audio_count += 1;
                name
            }
            matroska::Tracktype::Subtitle => {
                let name = format!("Subtitle#{}", subtitle_count);
                subtitle_count += 1;
                name
            }
            _ => "Unknown".to_string(),
        };

        Track {
            display_name,
            codec: t.codec_id.clone(),
            id: t.number,
            track_name: t.name.clone(),
            uid: t.uid,
            tags: Vec::new(),
        }
    }).collect();

    // 3. Process tags
    let mut global_tags = Vec::new();
    for tag in mkv.tags {
        let simple_tags: Vec<SimpleTag> = tag.simple.iter().map(|st| SimpleTag {
            name: st.name.clone(),
            string: match &st.value {
                Some(matroska::TagValue::String(s)) => s.clone(),
                _ => String::new(),
            },
            language: st.language.clone().map(|l| l.to_string()),
        }).collect();

        let is_global = tag.targets.as_ref().map_or(true, |t| t.track_uids.is_empty());

        if is_global {
            global_tags.extend(simple_tags);
        } else {
            if let Some(targets) = &tag.targets {
                for uid in &targets.track_uids {
                    if let Some(track) = tracks.iter_mut().find(|t| t.uid == *uid) {
                        track.tags.extend(simple_tags.clone());
                    }
                }
            }
        }
    }

    // 4. Finalize and return
    tracks.sort_by_key(|t| t.id);

    let result = FileData {
        global_tags,
        tracks,
    };
    log::debug!("[BACKEND] Sending file data to frontend:\n{:#?}", result);
    Ok(result)
}

/// Internal struct for serializing a `<Simple>` tag to XML.
#[derive(Debug, Serialize)]
struct XmlWriteSimpleTag<'a> {
    #[serde(rename = "Name")]
    name: &'a str,
    #[serde(rename = "String")]
    string: &'a str,
}

/// Internal struct for serializing a `<Targets>` element to XML.
#[derive(Debug, Serialize, Default)]
struct XmlWriteTargets {
    #[serde(rename = "TrackUID", default, skip_serializing_if = "Vec::is_empty")]
    track_uid: Vec<u64>,
}

/// Internal struct for serializing a `<Tag>` element to XML.
#[derive(Debug, Serialize)]
struct XmlWriteTag<'a> {
    #[serde(rename = "Targets")]
    targets: XmlWriteTargets,
    #[serde(rename = "Simple")]
    simple: Vec<XmlWriteSimpleTag<'a>>,
}

/// Internal struct for serializing the root `<Tags>` element to XML.
#[derive(Debug, Serialize)]
#[serde(rename = "Tags")]
struct XmlWriteTags<'a> {
    #[serde(rename = "Tag")]
    tag: Vec<XmlWriteTag<'a>>,
}

/// Converts the application's `FileData` struct into an XML string
/// compatible with `mkvpropedit`.
fn to_xml(data: &FileData) -> Result<String, quick_xml::se::SeError> {
    let mut xml_tags = Vec::new();

    if !data.global_tags.is_empty() {
        xml_tags.push(XmlWriteTag {
            targets: XmlWriteTargets::default(),
            simple: data
                .global_tags
                .iter()
                .map(|t| XmlWriteSimpleTag {
                    name: &t.name,
                    string: &t.string,
                })
                .collect(),
        });
    }

    for track in &data.tracks {
        if !track.tags.is_empty() {
            xml_tags.push(XmlWriteTag {
                targets: XmlWriteTargets {
                    track_uid: vec![track.uid],
                },
                simple: track
                    .tags
                    .iter()
                    .map(|t| XmlWriteSimpleTag {
                        name: &t.name,
                        string: &t.string,
                    })
                    .collect(),
            });
        }
    }

    let tags_to_serialize = XmlWriteTags { tag: xml_tags };
    quick_xml::se::to_string(&tags_to_serialize)
}


/// Saves the provided tag data back to the specified Matroska file.
///
/// This command receives the complete tag data as a JSON string from the frontend.
/// It then:
/// 1. Deserializes the JSON into the `FileData` struct.
/// 2. Serializes the `FileData` struct into a temporary XML file.
/// 3. Executes `mkvpropedit` to apply the tags from the XML file to the Matroska file.
///
/// # Arguments
///
/// * `path` - The absolute path to the Matroska file to be modified.
/// * `json_data` - A JSON string representing the `FileData` to be saved.
///
/// # Errors
///
/// This function will return an error if any step in the process fails, including
/// JSON parsing, XML generation, temporary file creation, or the `mkvpropedit` command execution.
#[tauri::command]
async fn save_file_data(path: String, json_data: String) -> Result<(), String> {
    log::info!("[BACKEND] Received save request for path: {}", path);
    log::debug!("[BACKEND] Raw JSON data received:\n{}", json_data);

    let file_data: FileData = serde_json::from_str(&json_data)
        .map_err(|e| format!("Failed to parse JSON data: {}", e))?;

    let xml_string =
        to_xml(&file_data).map_err(|e| format!("Failed to generate XML: {}", e))?;

    log::debug!("Generated XML:\n{}", xml_string);

    let mut temp_file = tempfile::Builder::new()
        .suffix(".xml")
        .tempfile()
        .map_err(|e| format!("Failed to create temporary file: {}", e))?;

    use std::io::Write;
    temp_file.write_all(xml_string.as_bytes())
        .map_err(|e| format!("Failed to write to temporary file: {}", e))?;

    let temp_path = temp_file.path().to_str().ok_or("Temporary file path is not valid UTF-8")?;

    log::info!("Running mkvpropedit on {}", path);
    let output = create_command("mkvpropedit")
        .arg(&path)
        .arg("--tags")
        .arg(format!("all:{}", temp_path))
        .output()
        .await
        .map_err(|e| format!("Failed to execute mkvpropedit: {}", e))?;

    if !output.status.success() {
        let error_message = String::from_utf8_lossy(&output.stderr);
        log::error!("mkvpropedit failed: {}", error_message);
        return Err(format!("mkvpropedit failed: {}", error_message));
    }

    log::info!("Successfully saved tags to {}", path);
    Ok(())
}


/// A command to forcefully close the application.
/// This is called by the frontend after a user confirms closing with unsaved changes.
#[tauri::command]
fn force_close(app: tauri::AppHandle) {
    app.exit(0);
}

/// The main entry point for the Tauri application logic.
/// This function sets up the Tauri application builder, registers plugins,
/// defines invoke handlers, and runs the application.
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_process::init())
        .plugin(
            tauri_plugin_log::Builder::new()
                .targets([
                    Target::new(TargetKind::Stdout),
                    Target::new(TargetKind::LogDir { file_name: None }),
                    Target::new(TargetKind::Webview),
                ])
                .build(),
        )
        .setup(|app| {
            let app_handle = app.handle().clone();
            tauri::async_runtime::spawn(async move {
                let commands = ["mkvpropedit"];
                let checks = commands.iter().map(|&command| async move {
                    log::info!("Checking for command: {}", command);
                    let check_command = if cfg!(target_os = "windows") { "where" } else { "which" };
                    let status = create_command(check_command).arg(command).output().await;

                    match status {
                        Ok(output) if output.status.success() => {
                            log::info!("Command found: {}", command);
                            None
                        }
                        _ => {
                            log::warn!("Command not found: {}", command);
                            Some(command.to_string())
                        }
                    }
                });

                let results: Vec<Option<String>> = future::join_all(checks).await;
                let not_found_commands: Vec<String> = results.into_iter().flatten().collect();

                if !not_found_commands.is_empty() {
                    let message = format!(
                        "The following required commands were not found:\n\n{}\n\nPlease install MKVToolNix and ensure it is in your system's PATH.",
                        not_found_commands.join("\n")
                    );

                    let dialog = app_handle.dialog().clone();
                    dialog
                        .message(message)
                        .title("Environment Check Failed")
                        .show(move |_| {
                            app_handle.exit(1);
                        });
                }
            });
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            greet,
            open_file_dialog,
            get_file_data,
            save_file_data,
            force_close,
            drop::create_drop_window,
            drop::hide_drop_window,
            drop::show_drop_window,
            drop::take_drop_files
        ])
        .on_window_event(|window, event| {
            if let tauri::WindowEvent::CloseRequested { api, .. } = event {
                api.prevent_close();
                let window = window.clone();
                window.emit("close-requested", {}).unwrap();
            }
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
